apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir-volume
spec:
  containers:
    - image: caddy
      name: caddy-container
      volumeMounts:
      - mountPath: /mounted-data
        name: data-volume
  volumes:
  - name: data-volume
    emptyDir: {}
